export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
export const GET_RECIPE_DETAIL = "GET_RECIPE_DETAIL";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const GET_DIETS_TYPES = "GET_DIETS_TYPES";
